backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "assets/gallery"
public_folder: "/assets/gallery"

collections:
  - name: "menu"
    label: "Menu"
    folder: "assets/menu"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nom du plat", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Prix", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "avis"
    label: "Avis Clients"
    folder: "assets/avis"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nom du client", name: "name", widget: "string" }
      - { label: "Message", name: "message", widget: "text" }
