backend:
  name: git-gateway
  branch: main

media_folder: "assets/gallery"
public_folder: "/assets/gallery"

collections:
  - name: "menus"
    label: "Menu"
    folder: "assets/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nom du plat", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Prix", name: "price", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }
