backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "media"
    label: "Biblioth√®que d'images"
    label_singular: "Image"
    folder: "assets"
    create: true
    fields:
      - { label: "Fichier", name: "image", widget: "image" }
